inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/**/*'
  Max: 80
