inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/**/*'
  Max: 80

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/RegexpLiteral:
  Enabled: false
