version: '3.8'
services:

  db:
    image: 'mysql:8.0'
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 33070:3306
    volumes:
      - db-volume:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s --binding=0.0.0.0 --port=3000
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      # cache directories on the container only
      - /app/node_modules
      - /app/tmp
      # mount the rest of the source directory to container
      - .:/app
    environment:
      DATABASE_HOST: db

volumes:
  db-volume:
